[package]
name = "experiment00"
version = "0.1.0"
authors = ["Kai Yao <kai.b.yao@gmail.com>"]
edition = "2018"

[lib]
name = "experiment00"
path = "src/lib.rs"

[[bin]]
name = "experiment00bin"
path = "src/main.rs"

# [[bin]]
# name = "experiment00test"
# path = "src/test.rs"

[dependencies]
actix-web = "^0.7"
failure = "^0.1"
futures = "^0.1"
lazy_static = "^1.2"
num_cpus = "^1.9"
r2d2 = "^0.8"
r2d2_postgres = "^0.14"
regex = "^1.1"
serde = "^1.0"
serde_derive = "^1.0"
# serde_json = "^1.0"

[dev-dependencies]
clippy = "^0.0.3"
pretty_assertions = "^0.5"
