[package]
name = "experiment00"
version = "0.1.0"
authors = ["Kai Yao <kai.b.yao@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "~0.7"
postgres = "~0.15"
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"
