version: '3.1'

services:
  db:
    image: postgres
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    restart: always
    environment:
      POSTGRES_PASSWORD: example # user = postgres
    ports:
      - 5433:5432
    volumes:
      - ./rust-postgres-rest/tests/server.crt:/var/lib/postgresql/server.crt
      - ./rust-postgres-rest/tests/server.key:/var/lib/postgresql/server.key
